# Generated by Django 6.0.6 on 2026-07-10 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(max_length=80)),
                ('hero_title', models.CharField(max_length=120)),
                ('hero_subtitle', models.CharField(max_length=255)),
                ('hero_background', models.ImageField(blank=True, null=True, upload_to='home/hero/')),
                ('about_eyebrow', models.CharField(max_length=80)),
                ('about_title', models.CharField(max_length=200)),
                ('about_body', models.TextField()),
                ('about_cta_label', models.CharField(max_length=80)),
                ('about_cta_url', models.CharField(max_length=255)),
                ('about_social_label', models.CharField(default='Síguenos', max_length=80)),
                ('featured_eyebrow', models.CharField(max_length=80)),
                ('featured_title', models.CharField(max_length=120)),
                ('featured_empty_message', models.TextField()),
                ('featured_links', models.JSONField(default=list)),
                ('zones_eyebrow', models.CharField(max_length=80)),
                ('zones_title', models.CharField(max_length=120)),
                ('zones_description', models.TextField()),
                ('zones_cta_label', models.CharField(max_length=80)),
                ('zones_cta_url', models.CharField(max_length=255)),
                ('contact_eyebrow', models.CharField(max_length=80)),
                ('contact_title', models.CharField(max_length=120)),
                ('contact_description', models.TextField()),
                ('contact_cta_label', models.CharField(max_length=80)),
                ('contact_cta_url', models.CharField(max_length=255)),
                ('expertise_title', models.CharField(max_length=200)),
                ('expertise_subtitle', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de inicio',
                'verbose_name_plural': 'Página de inicio',
            },
        ),
        migrations.CreateModel(
            name='HomeCityHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aria_label', models.CharField(max_length=200)),
                ('city_name', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_desktop', models.ImageField(blank=True, null=True, upload_to='home/city/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='home/city/mobile/')),
                ('external_desktop_url', models.URLField(blank=True, max_length=500)),
                ('external_mobile_url', models.URLField(blank=True, max_length=500)),
                ('home_page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='city_highlight', to='site_content.homepage')),
            ],
            options={
                'verbose_name': 'Destacado ciudad (inicio)',
                'verbose_name_plural': 'Destacado ciudad (inicio)',
            },
        ),
        migrations.CreateModel(
            name='HomeAboutSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/about/')),
                ('image_mobile', models.ImageField(blank=True, null=True, upload_to='home/about/mobile/')),
                ('alt_text', models.CharField(max_length=200)),
                ('external_url', models.URLField(blank=True, help_text='URL externa de respaldo si no hay imagen subida.', max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_slides', to='site_content.homepage')),
            ],
            options={
                'verbose_name': 'Imagen carrusel Nosotros (inicio)',
                'verbose_name_plural': 'Imágenes carrusel Nosotros (inicio)',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeExpertiseService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('bullets', models.JSONField(default=list)),
                ('icon', models.CharField(default='Building2', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_services', to='site_content.homepage')),
            ],
            options={
                'verbose_name': 'Servicio de asesoría (inicio)',
                'verbose_name_plural': 'Servicios de asesoría (inicio)',
                'ordering': ['order', 'id'],
                'unique_together': {('home_page', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='HomeExpertisePillar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('bento_class', models.CharField(blank=True, default='', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expertise_pillars', to='site_content.homepage')),
            ],
            options={
                'verbose_name': 'Pilar de asesoría (inicio)',
                'verbose_name_plural': 'Pilares de asesoría (inicio)',
                'ordering': ['order', 'id'],
                'unique_together': {('home_page', 'slug')},
            },
        ),
    ]
