# Generated by Django 6.0.6 on 2026-07-13 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_video',
            field=models.FileField(blank=True, null=True, upload_to='home/hero/video/'),
        ),
        migrations.CreateModel(
            name='HomeJournalPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('text', 'Texto'), ('image', 'Imagen'), ('video', 'Video')], default='text', max_length=10)),
                ('category', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('date_label', models.CharField(blank=True, default='', max_length=40)),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/journal/')),
                ('video', models.FileField(blank=True, null=True, upload_to='home/journal/video/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('home_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='journal_posts', to='site_content.homepage')),
            ],
            options={
                'verbose_name': 'Post del feed (inicio)',
                'verbose_name_plural': 'Posts del feed (inicio)',
                'ordering': ['order', 'id'],
            },
        ),
    ]
