# Generated by Django 6.0.6 on 2026-07-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_content', '0002_home_hero_video_and_journal_posts'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='content_en',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
