# Generated by Django 6.0.6 on 2026-07-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('tagline', models.CharField(blank=True, max_length=255)),
                ('developer', models.CharField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('zone', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(default='Querétaro', max_length=80)),
                ('state', models.CharField(default='Querétaro', max_length=80)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Preventa', 'Preventa'), ('En construcción', 'En construcción'), ('Entrega inmediata', 'Entrega inmediata')], default='Preventa', max_length=40)),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('currency', models.CharField(default='MXN', max_length=3)),
                ('delivery', models.CharField(blank=True, max_length=80)),
                ('unit_types', models.JSONField(blank=True, default=list)),
                ('bedrooms_min', models.PositiveSmallIntegerField(default=1)),
                ('bedrooms_max', models.PositiveSmallIntegerField(default=1)),
                ('area_min', models.PositiveIntegerField(default=0)),
                ('area_max', models.PositiveIntegerField(default=0)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='developments/covers/')),
                ('cover_image_external_url', models.URLField(blank=True, max_length=500)),
                ('total_units', models.PositiveIntegerField(default=0)),
                ('featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Desarrollo',
                'verbose_name_plural': 'Desarrollos',
                'ordering': ['order', '-featured', '-updated_at', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(max_length=80)),
                ('hero_title', models.CharField(max_length=160)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='developments/page/hero/')),
                ('hero_image_external_url', models.URLField(blank=True, max_length=500)),
                ('empty_message', models.TextField()),
                ('empty_cta_label', models.CharField(default='Contactar asesor', max_length=80)),
                ('empty_cta_url', models.CharField(default='/contacto', max_length=255)),
                ('meta_title', models.CharField(blank=True, max_length=160)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de desarrollos (textos)',
                'verbose_name_plural': 'Página de desarrollos (textos)',
            },
        ),
        migrations.CreateModel(
            name='DevelopmentGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='developments/gallery/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('order', models.PositiveIntegerField(default=0)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='developments.development')),
            ],
            options={
                'verbose_name': 'Imagen de galería',
                'verbose_name_plural': 'Imágenes de galería',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentUnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120)),
                ('name', models.CharField(max_length=160)),
                ('bedrooms', models.PositiveSmallIntegerField(default=1)),
                ('bathrooms', models.PositiveSmallIntegerField(default=1)),
                ('half_bathrooms', models.PositiveSmallIntegerField(default=0)),
                ('area_m2', models.PositiveIntegerField(default=0)),
                ('lot_m2', models.PositiveIntegerField(blank=True, null=True)),
                ('parking', models.PositiveSmallIntegerField(default=0)),
                ('price_from', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('list_price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='developments/models/')),
                ('cover_image_external_url', models.URLField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('available', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_models', to='developments.development')),
            ],
            options={
                'verbose_name': 'Modelo de unidad',
                'verbose_name_plural': 'Modelos de unidad',
                'ordering': ['order', 'id'],
                'unique_together': {('development', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='DevelopmentModelImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='developments/models/gallery/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='developments.developmentunitmodel')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DevelopmentFloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('image', models.ImageField(blank=True, null=True, upload_to='developments/models/plans/')),
                ('external_url', models.URLField(blank=True, max_length=500)),
                ('order', models.PositiveIntegerField(default=0)),
                ('unit_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_plans', to='developments.developmentunitmodel')),
            ],
            options={
                'verbose_name': 'Planta arquitectónica',
                'verbose_name_plural': 'Plantas arquitectónicas',
                'ordering': ['order', 'id'],
            },
        ),
    ]
