# Generated by Django 6.0.6 on 2026-07-10 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('developments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='developmentunitmodel',
            name='tour_enabled',
            field=models.BooleanField(default=False, help_text='Si está activo, se muestra el embed en la ficha pública.'),
        ),
        migrations.AddField(
            model_name='developmentunitmodel',
            name='tour_id',
            field=models.CharField(blank=True, help_text='ID limpio del space (ej. Matterport m=XXXXXXXXXXX).', max_length=64),
        ),
        migrations.AddField(
            model_name='developmentunitmodel',
            name='tour_provider',
            field=models.CharField(blank=True, default='matterport', help_text='Proveedor del tour 3D (matterport, …).', max_length=32),
        ),
        migrations.AddField(
            model_name='developmentunitmodel',
            name='tour_title',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='developmentunitmodel',
            name='tour_url',
            field=models.URLField(blank=True, help_text='URL original pegada en el dashboard.', max_length=500),
        ),
    ]
