# Generated by Django 6.0.6 on 2026-07-13 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_description', models.TextField(blank=True)),
                ('channels', models.JSONField(blank=True, default=list)),
                ('form_title', models.CharField(blank=True, max_length=200)),
                ('form_description', models.TextField(blank=True)),
                ('form_name_label', models.CharField(blank=True, max_length=80)),
                ('form_name_placeholder', models.CharField(blank=True, max_length=160)),
                ('form_phone_label', models.CharField(blank=True, max_length=80)),
                ('form_phone_hint', models.CharField(blank=True, max_length=80)),
                ('form_phone_placeholder', models.CharField(blank=True, max_length=160)),
                ('form_email_label', models.CharField(blank=True, max_length=80)),
                ('form_email_placeholder', models.CharField(blank=True, max_length=160)),
                ('form_message_label', models.CharField(blank=True, max_length=120)),
                ('form_message_placeholder', models.CharField(blank=True, max_length=240)),
                ('form_quick_prompts_label', models.CharField(blank=True, max_length=80)),
                ('form_quick_prompts', models.JSONField(blank=True, default=list)),
                ('form_submit_label', models.CharField(blank=True, max_length=80)),
                ('form_submitting_label', models.CharField(blank=True, max_length=80)),
                ('form_success_title', models.CharField(blank=True, max_length=120)),
                ('form_success_message', models.TextField(blank=True)),
                ('form_reset_label', models.CharField(blank=True, max_length=80)),
                ('reassurance_title', models.CharField(blank=True, max_length=120)),
                ('reassurance_items', models.JSONField(blank=True, default=list)),
                ('reassurance_footer', models.CharField(blank=True, max_length=200)),
                ('property_banner_label', models.CharField(blank=True, max_length=80)),
                ('property_banner_cta', models.CharField(blank=True, max_length=80)),
                ('property_form_label', models.CharField(blank=True, max_length=80)),
                ('seo_title', models.CharField(blank=True, max_length=160)),
                ('seo_description', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Contacto (textos)',
                'verbose_name_plural': 'Página Contacto (textos)',
            },
        ),
    ]
