# Generated by Django 6.0.6 on 2026-07-07 07:54

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Título')),
                ('category', models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta'), ('Desarrollo', 'Desarrollo')], max_length=20, verbose_name='Categoría')),
                ('price', models.DecimalField(decimal_places=2, max_digits=14, verbose_name='Precio')),
                ('currency', models.CharField(default='MXN', max_length=3, verbose_name='Moneda')),
                ('bedrooms', models.PositiveIntegerField(verbose_name='Recámaras')),
                ('bathrooms', models.PositiveIntegerField(verbose_name='Baños')),
                ('surface_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Superficie (m²)')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326, verbose_name='Ubicación (lat/lng)')),
                ('address_details', models.CharField(help_text='Ej. "El Marqués, Querétaro"', max_length=255, verbose_name='Detalles de dirección')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Destacada')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creada el')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Actualizada el')),
            ],
            options={
                'verbose_name': 'Propiedad',
                'verbose_name_plural': 'Propiedades',
                'ordering': ['-created_at'],
            },
        ),
    ]
