# Generated by Django 6.0.6 on 2026-07-07 21:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_operational_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='bedrooms',
            field=models.PositiveIntegerField(default=0, verbose_name='Recámaras'),
        ),
        migrations.AlterField(
            model_name='property',
            name='operation_type',
            field=models.CharField(choices=[('Venta', 'Venta'), ('Renta', 'Renta'), ('Venta o Renta', 'Venta o Renta')], max_length=20, verbose_name='Tipo de operación'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('Casa', 'Casa'), ('Departamento', 'Departamento'), ('Terreno', 'Terreno'), ('Condominio', 'Condominio'), ('Casa en condominio', 'Casa en condominio'), ('Penthouse', 'Penthouse'), ('Local Comercial', 'Local Comercial'), ('Oficina', 'Oficina'), ('Consultorio', 'Consultorio'), ('Bodega', 'Bodega'), ('Nave industrial', 'Nave industrial'), ('Rancho', 'Rancho'), ('Otro', 'Otro')], max_length=30, verbose_name='Tipo de propiedad'),
        ),
        migrations.AlterField(
            model_name='property',
            name='state',
            field=models.CharField(choices=[('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Durango', 'Durango'), ('Estado de México', 'Estado de México'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=40, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(choices=[('Zona Campanario / Altozano', 'Zona Campanario / Altozano'), ('Zona Centro / Querétaro Tradicional', 'Zona Centro / Querétaro Tradicional'), ('Zona Centro Sur / Sur de Querétaro', 'Zona Centro Sur / Sur de Querétaro'), ('Zona Ciudad del Sol / Poniente', 'Zona Ciudad del Sol / Poniente'), ('Zona Corregidora', 'Zona Corregidora'), ('Zona El Refugio / Norte de El Marqués', 'Zona El Refugio / Norte de El Marqués'), ('Zona Juriquilla / Jurica', 'Zona Juriquilla / Jurica'), ('Zona Zibatá / Zakia', 'Zona Zibatá / Zakia')], max_length=80, verbose_name='Zona de Querétaro'),
        ),
        migrations.CreateModel(
            name='PropertyPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='properties/%Y/%m/', verbose_name='Imagen')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Orden')),
                ('is_cover', models.BooleanField(default=False, verbose_name='Portada')),
                ('alt_text', models.CharField(blank=True, max_length=255, verbose_name='Texto alternativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Subida el')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='properties.property', verbose_name='Propiedad')),
            ],
            options={
                'verbose_name': 'Foto de propiedad',
                'verbose_name_plural': 'Fotos de propiedades',
                'ordering': ['order', 'id'],
            },
        ),
    ]
