# Generated by Django 6.0.6 on 2026-07-08 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_property_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='easybroker_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='ID EasyBroker'),
        ),
        migrations.AddField(
            model_name='property',
            name='easybroker_synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última sync EasyBroker'),
        ),
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(choices=[('Zona Campanario / Altozano', 'Zona Campanario / Altozano'), ('Zona Centro / Querétaro Tradicional', 'Zona Centro / Querétaro Tradicional'), ('Zona Centro Sur / Sur de Querétaro', 'Zona Centro Sur / Sur de Querétaro'), ('Zona Ciudad del Sol / Poniente', 'Zona Ciudad del Sol / Poniente'), ('Zona Corregidora', 'Zona Corregidora'), ('Zona El Refugio / Norte de El Marqués', 'Zona El Refugio / Norte de El Marqués'), ('Zona Juriquilla / Jurica', 'Zona Juriquilla / Jurica'), ('Zona Zibatá / Zakia', 'Zona Zibatá / Zakia'), ('Otra / Sin clasificar', 'Otra / Sin clasificar')], max_length=80, verbose_name='Zona de Querétaro'),
        ),
    ]
