# Generated by Django 6.0.6 on 2026-07-14 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0006_property_technical_sheet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='zone',
            field=models.CharField(choices=[('Zona Campanario / Altozano', 'Zona Campanario / Altozano'), ('Zona Centro / Querétaro Tradicional', 'Zona Centro / Querétaro Tradicional'), ('Zona Centro Sur / Sur de Querétaro', 'Zona Centro Sur / Sur de Querétaro'), ('Zona Ciudad del Sol / Poniente', 'Zona Ciudad del Sol / Poniente'), ('Zona Corregidora', 'Zona Corregidora'), ('Zona El Refugio / Norte de El Marqués', 'Zona El Refugio / Norte de El Marqués'), ('Zona Juriquilla / Jurica', 'Zona Juriquilla / Jurica'), ('Zona Zibatá / Zakia', 'Zona Zibatá / Zakia'), ('Zona Industrial / Logística', 'Zona Industrial / Logística'), ('Otra / Sin clasificar', 'Otra / Sin clasificar')], max_length=80, verbose_name='Zona de Querétaro'),
        ),
    ]
