"""Datos de ejemplo (antes mock del frontend) para sembrar desarrollos."""

from __future__ import annotations

PLAN_IMAGES = [
    "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1470&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=1470&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=1470&auto=format&fit=crop",
    "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=1470&auto=format&fit=crop",
]

SEED_DEVELOPMENTS: list[dict] = [
    {
        "slug": "altaria-zibata",
        "name": "Altaria Zibatá",
        "tagline": "Vida vertical con vistas al campo de golf",
        "developer": "Grupo Altaria",
        "zone": "Zona Zibatá / Zakia",
        "city": "El Marqués",
        "state": "Querétaro",
        "address": "Blvd. Zibatá 100, Zibatá",
        "latitude": 20.6835,
        "longitude": -100.3162,
        "status": "Preventa",
        "price_from": 3250000,
        "currency": "MXN",
        "delivery": "Q4 2027",
        "unit_types": ["Departamentos", "Penthouses"],
        "bedrooms_min": 1,
        "bedrooms_max": 3,
        "area_min": 68,
        "area_max": 210,
        "amenities": [
            "Rooftop infinity",
            "Gimnasio panorámico",
            "Coworking",
            "Alberca",
            "Seguridad 24/7",
            "Salón de usos múltiples",
            "Área de asadores",
            "Pet friendly",
        ],
        "cover_image_external_url": "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2080&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1567767292278-a4f21aa2d36e?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 96,
        "featured": True,
        "is_published": True,
        "order": 0,
        "description": (
            "Torre residencial de autor en el corazón de Zibatá, "
            "con amenidades tipo resort y acabados de lujo."
        ),
        "models": [
            {
                "slug": "domi-pb",
                "name": "DOMI PB",
                "bedrooms": 1,
                "bathrooms": 1,
                "half_bathrooms": 0,
                "area_m2": 68,
                "lot_m2": None,
                "parking": 1,
                "price_from": 3250000,
                "list_price": 3480000,
                "cover_image_external_url": "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2080&auto=format&fit=crop",
                "description": "Unidad de planta baja con jardín privado y acceso directo a amenidades.",
                "features": [
                    "Habitación principal con baño completo",
                    "Cocina integral equipada",
                    "Jardín privado en planta baja",
                    "Un lugar de estacionamiento",
                ],
                "gallery": [
                    "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2080&auto=format&fit=crop",
                    "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
                    "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?q=80&w=2070&auto=format&fit=crop",
                ],
                "floor_plans": [{"label": "Planta baja", "image": PLAN_IMAGES[0]}],
                "available": 6,
                "order": 0,
            },
            {
                "slug": "domi-loft",
                "name": "DOMI Loft",
                "bedrooms": 2,
                "bathrooms": 2,
                "half_bathrooms": 1,
                "area_m2": 112,
                "lot_m2": None,
                "parking": 1,
                "price_from": 4650000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?q=80&w=2070&auto=format&fit=crop",
                "description": "Doble altura con ventanales de piso a techo y vista al campo de golf.",
                "features": [
                    "Doble altura con ventanales de piso a techo",
                    "Habitación principal con walking closet",
                    "Habitación secundaria con baño completo",
                    "Medio baño de visitas",
                    "Área de lavado interior",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                ],
                "available": 10,
                "order": 1,
            },
            {
                "slug": "domi-sky",
                "name": "DOMI Sky",
                "bedrooms": 3,
                "bathrooms": 3,
                "half_bathrooms": 1,
                "area_m2": 210,
                "lot_m2": None,
                "parking": 2,
                "price_from": 7900000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?q=80&w=2070&auto=format&fit=crop",
                "description": "Penthouse con roof garden privado, ideal para quien busca lo máximo.",
                "features": [
                    "Roof garden privado con jacuzzi",
                    "Sala, comedor y family room",
                    "Cocina con isla y despensa",
                    "Dos lugares de estacionamiento techados",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta principal", "image": PLAN_IMAGES[1]},
                    {"label": "Roof garden", "image": PLAN_IMAGES[2]},
                ],
                "available": 3,
                "order": 2,
            },
        ],
    },
    {
        "slug": "reserva-juriquilla",
        "name": "Reserva Juriquilla",
        "tagline": "Residencias jardín en un enclave privado",
        "developer": "Desarrolladora Península",
        "zone": "Zona Juriquilla / Jurica",
        "city": "Querétaro",
        "state": "Querétaro",
        "address": "Anillo Vial Fray Junípero Serra 8000, Juriquilla",
        "latitude": 20.7031,
        "longitude": -100.4469,
        "status": "En construcción",
        "price_from": 5900000,
        "currency": "MXN",
        "delivery": "Q2 2026",
        "unit_types": ["Casas", "Townhouses"],
        "bedrooms_min": 3,
        "bedrooms_max": 4,
        "area_min": 180,
        "area_max": 320,
        "amenities": [
            "Casa club",
            "Alberca",
            "Áreas verdes",
            "Acceso controlado",
            "Cancha de pádel",
            "Juegos infantiles",
        ],
        "cover_image_external_url": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600585152220-90363fe7e115?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600585153490-76fb20a32601?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 42,
        "featured": False,
        "is_published": True,
        "order": 1,
        "description": "Comunidad de casas contemporáneas rodeadas de naturaleza, con amenidades familiares.",
        "models": [
            {
                "slug": "roble-pb",
                "name": "Roble PB",
                "bedrooms": 3,
                "bathrooms": 2,
                "half_bathrooms": 1,
                "area_m2": 180,
                "lot_m2": 200,
                "parking": 2,
                "price_from": 5900000,
                "list_price": 6250000,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?q=80&w=2070&auto=format&fit=crop",
                "description": "Casa de una planta con jardín amplio y estancia integrada.",
                "features": [
                    "Habitación principal con baño completo y vestidor",
                    "Dos habitaciones secundarias",
                    "Jardín amplio",
                    "Área de lavado interior",
                    "Dos lugares de estacionamiento",
                ],
                "gallery": [],
                "floor_plans": [{"label": "Planta baja", "image": PLAN_IMAGES[0]}],
                "available": 8,
                "order": 0,
            },
            {
                "slug": "encino",
                "name": "Encino",
                "bedrooms": 4,
                "bathrooms": 3,
                "half_bathrooms": 1,
                "area_m2": 320,
                "lot_m2": 280,
                "parking": 3,
                "price_from": 8400000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?q=80&w=2070&auto=format&fit=crop",
                "description": "Residencia de dos niveles con estudio, family room y roof.",
                "features": [
                    "Habitación principal con baño y walking closet",
                    "Estudio en planta baja",
                    "Family room en planta alta",
                    "Roof con área de asador",
                    "Tres lugares de estacionamiento",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                    {"label": "Roof", "image": PLAN_IMAGES[2]},
                ],
                "available": 4,
                "order": 1,
            },
        ],
    },
    {
        "slug": "distrito-central",
        "name": "Distrito Central",
        "tagline": "Lofts urbanos en el nuevo corazón de la ciudad",
        "developer": "Central Living",
        "zone": "Zona Centro Sur / Sur de Querétaro",
        "city": "Querétaro",
        "state": "Querétaro",
        "address": "Av. 5 de Febrero 1200, Centro Sur",
        "latitude": 20.5732,
        "longitude": -100.4021,
        "status": "Entrega inmediata",
        "price_from": 2450000,
        "currency": "MXN",
        "delivery": "Inmediata",
        "unit_types": ["Lofts", "Departamentos"],
        "bedrooms_min": 1,
        "bedrooms_max": 2,
        "area_min": 55,
        "area_max": 120,
        "amenities": [
            "Sky lounge",
            "Business center",
            "Pet friendly",
            "Ciclopuertos",
            "Gimnasio",
            "Terraza",
        ],
        "cover_image_external_url": "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2080&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 128,
        "featured": False,
        "is_published": True,
        "order": 2,
        "description": "Lofts de líneas limpias listos para habitar, conectados con la vida cultural de la ciudad.",
        "models": [
            {
                "slug": "loft-uno",
                "name": "Loft Uno",
                "bedrooms": 1,
                "bathrooms": 1,
                "half_bathrooms": 0,
                "area_m2": 55,
                "lot_m2": None,
                "parking": 1,
                "price_from": 2450000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1493809842364-78817add7ffb?q=80&w=2070&auto=format&fit=crop",
                "description": "Loft de espacio abierto, listo para habitar.",
                "features": [
                    "Espacio abierto tipo loft",
                    "Cocina integral equipada",
                    "Baño completo",
                    "Un lugar de estacionamiento",
                ],
                "gallery": [],
                "floor_plans": [{"label": "Planta única", "image": PLAN_IMAGES[3]}],
                "available": 12,
                "order": 0,
            },
            {
                "slug": "duo",
                "name": "Duo",
                "bedrooms": 2,
                "bathrooms": 2,
                "half_bathrooms": 0,
                "area_m2": 120,
                "lot_m2": None,
                "parking": 1,
                "price_from": 3850000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1524758631624-e2822e304c36?q=80&w=2070&auto=format&fit=crop",
                "description": "Departamento de dos recámaras con balcón urbano.",
                "features": [
                    "Dos habitaciones con baño completo",
                    "Balcón con vista urbana",
                    "Cocina integral",
                    "Área de lavado",
                ],
                "gallery": [],
                "floor_plans": [{"label": "Planta única", "image": PLAN_IMAGES[2]}],
                "available": 5,
                "order": 1,
            },
        ],
    },
    {
        "slug": "campo-altozano",
        "name": "Campo Altozano",
        "tagline": "Villas de montaña con arquitectura de autor",
        "developer": "Altozano Living",
        "zone": "Zona Campanario / Altozano",
        "city": "Querétaro",
        "state": "Querétaro",
        "address": "Camino a Los Olvera s/n, Altozano",
        "latitude": 20.5288,
        "longitude": -100.3719,
        "status": "Preventa",
        "price_from": 8900000,
        "currency": "MXN",
        "delivery": "Q1 2028",
        "unit_types": ["Villas", "Residencias"],
        "bedrooms_min": 3,
        "bedrooms_max": 5,
        "area_min": 280,
        "area_max": 520,
        "amenities": ["Spa", "Wine bar", "Cancha de pádel", "Concierge", "Alberca", "Gimnasio"],
        "cover_image_external_url": "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1613977257363-707ba9348227?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1613490900233-141c5560d75d?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600047508788-26bb381e2d2b?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 24,
        "featured": False,
        "is_published": True,
        "order": 3,
        "description": "Villas exclusivas en las alturas de Altozano, con vistas panorámicas y máxima privacidad.",
        "models": [
            {
                "slug": "villa-cima",
                "name": "Villa Cima",
                "bedrooms": 3,
                "bathrooms": 3,
                "half_bathrooms": 1,
                "area_m2": 280,
                "lot_m2": 320,
                "parking": 2,
                "price_from": 8900000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600585154526-990dced4db0d?q=80&w=2070&auto=format&fit=crop",
                "description": "Villa con vistas panorámicas y doble terraza.",
                "features": [
                    "Habitación principal con terraza privada",
                    "Doble altura en estancia",
                    "Cava y bar",
                    "Dos terrazas panorámicas",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                ],
                "available": 6,
                "order": 0,
            },
            {
                "slug": "villa-cumbre",
                "name": "Villa Cumbre",
                "bedrooms": 5,
                "bathrooms": 5,
                "half_bathrooms": 1,
                "area_m2": 520,
                "lot_m2": 600,
                "parking": 4,
                "price_from": 15900000,
                "list_price": 16900000,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600566752355-35792bedcfea?q=80&w=2070&auto=format&fit=crop",
                "description": "Residencia insignia con alberca privada, cava y home theater.",
                "features": [
                    "Alberca privada climatizada",
                    "Home theater y cava",
                    "Habitación principal con lounge",
                    "Cuarto de servicio independiente",
                    "Cuatro cajones de estacionamiento",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Sótano", "image": PLAN_IMAGES[3]},
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                    {"label": "Roof", "image": PLAN_IMAGES[2]},
                ],
                "available": 2,
                "order": 1,
            },
        ],
    },
    {
        "slug": "corredor-refugio",
        "name": "Corredor El Refugio",
        "tagline": "Departamentos smart para nuevas generaciones",
        "developer": "Refugio Urbano",
        "zone": "Zona El Refugio / Norte de El Marqués",
        "city": "Querétaro",
        "state": "Querétaro",
        "address": "Paseo de la República 15000, El Refugio",
        "latitude": 20.665,
        "longitude": -100.354,
        "status": "En construcción",
        "price_from": 1990000,
        "currency": "MXN",
        "delivery": "Q3 2026",
        "unit_types": ["Departamentos"],
        "bedrooms_min": 1,
        "bedrooms_max": 2,
        "area_min": 48,
        "area_max": 95,
        "amenities": ["Roof garden", "Gimnasio", "Domótica", "Coworking", "Seguridad 24/7"],
        "cover_image_external_url": "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1580587771525-78b9dba3b914?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?q=80&w=2080&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1502005229762-cf1b2da7c5d6?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 84,
        "featured": False,
        "is_published": True,
        "order": 4,
        "description": "Vivienda inteligente y eficiente en una de las zonas de mayor plusvalía de Querétaro.",
        "models": [
            {
                "slug": "smart-1",
                "name": "Smart 1",
                "bedrooms": 1,
                "bathrooms": 1,
                "half_bathrooms": 0,
                "area_m2": 48,
                "lot_m2": None,
                "parking": 1,
                "price_from": 1990000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1554995207-c18c203602cb?q=80&w=2070&auto=format&fit=crop",
                "description": "Departamento compacto con domótica integrada.",
                "features": [
                    "Domótica integrada",
                    "Cocina equipada",
                    "Baño completo",
                    "Un lugar de estacionamiento",
                ],
                "gallery": [],
                "floor_plans": [{"label": "Planta única", "image": PLAN_IMAGES[3]}],
                "available": 20,
                "order": 0,
            },
            {
                "slug": "smart-2",
                "name": "Smart 2",
                "bedrooms": 2,
                "bathrooms": 2,
                "half_bathrooms": 0,
                "area_m2": 95,
                "lot_m2": None,
                "parking": 1,
                "price_from": 2950000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1560185007-cde436f6a4d0?q=80&w=2070&auto=format&fit=crop",
                "description": "Dos recámaras con balcón y cocina equipada.",
                "features": ["Dos habitaciones", "Balcón", "Cocina equipada", "Área de lavado"],
                "gallery": [],
                "floor_plans": [{"label": "Planta única", "image": PLAN_IMAGES[2]}],
                "available": 14,
                "order": 1,
            },
        ],
    },
    {
        "slug": "jardines-corregidora",
        "name": "Jardines Corregidora",
        "tagline": "Un desarrollo pensado para la vida en familia",
        "developer": "Grupo Corregidora",
        "zone": "Zona Corregidora",
        "city": "Corregidora",
        "state": "Querétaro",
        "address": "Prol. Bernardo Quintana 500, El Pueblito",
        "latitude": 20.5451,
        "longitude": -100.4433,
        "status": "Entrega inmediata",
        "price_from": 4200000,
        "currency": "MXN",
        "delivery": "Inmediata",
        "unit_types": ["Casas"],
        "bedrooms_min": 3,
        "bedrooms_max": 4,
        "area_min": 160,
        "area_max": 240,
        "amenities": [
            "Casa club",
            "Alberca",
            "Juegos infantiles",
            "Seguridad 24/7",
            "Áreas verdes",
        ],
        "cover_image_external_url": "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop",
        "gallery": [
            "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600607687644-c7171b42498b?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1600566752229-250ed79470f8?q=80&w=2070&auto=format&fit=crop",
            "https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?q=80&w=2070&auto=format&fit=crop",
        ],
        "total_units": 58,
        "featured": False,
        "is_published": True,
        "order": 5,
        "description": "Casas amplias listas para entrega, con amenidades y áreas verdes para toda la familia.",
        "models": [
            {
                "slug": "jardin-pb",
                "name": "Jardín PB",
                "bedrooms": 3,
                "bathrooms": 2,
                "half_bathrooms": 1,
                "area_m2": 160,
                "lot_m2": 160,
                "parking": 2,
                "price_from": 4200000,
                "list_price": 4450000,
                "cover_image_external_url": "https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?q=80&w=2070&auto=format&fit=crop",
                "description": "Casa lista para entrega con jardín y cochera techada.",
                "features": [
                    "Habitación principal con baño completo",
                    "Dos habitaciones secundarias",
                    "Jardín trasero",
                    "Cochera techada para dos autos",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                ],
                "available": 9,
                "order": 0,
            },
            {
                "slug": "jardin-plus",
                "name": "Jardín Plus",
                "bedrooms": 4,
                "bathrooms": 3,
                "half_bathrooms": 1,
                "area_m2": 240,
                "lot_m2": 200,
                "parking": 2,
                "price_from": 5600000,
                "list_price": None,
                "cover_image_external_url": "https://images.unsplash.com/photo-1600607687644-c7171b42498b?q=80&w=2070&auto=format&fit=crop",
                "description": "Casa amplia de dos niveles con family room y estudio.",
                "features": [
                    "Habitación principal con vestidor",
                    "Estudio en planta baja",
                    "Family room en planta alta",
                    "Jardín y terraza",
                ],
                "gallery": [],
                "floor_plans": [
                    {"label": "Planta baja", "image": PLAN_IMAGES[0]},
                    {"label": "Planta alta", "image": PLAN_IMAGES[1]},
                ],
                "available": 5,
                "order": 1,
            },
        ],
    },
]
