# Generated by Django 6.0.6 on 2026-07-07 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('profile_photo', models.ImageField(blank=True, upload_to='agents/', verbose_name='Foto de perfil')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
                ('phone', models.CharField(max_length=20, verbose_name='Teléfono (WhatsApp)')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('status', models.CharField(choices=[('Nuevo', 'Nuevo'), ('En Contacto', 'En Contacto'), ('Negociación', 'Negociación'), ('Cerrado', 'Cerrado')], default='Nuevo', max_length=20, verbose_name='Estatus')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado el')),
                ('interested_in', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='properties.property', verbose_name='Interés en propiedad')),
            ],
            options={
                'verbose_name': 'Prospecto',
                'verbose_name_plural': 'Prospectos',
                'ordering': ['-created_at'],
            },
        ),
    ]
