# Generated by Django 6.0.6 on 2026-07-11 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('philosophy_title', models.CharField(max_length=160)),
                ('philosophy_subtitle', models.CharField(blank=True, max_length=200)),
                ('philosophy_intro_lines', models.JSONField(blank=True, default=list)),
                ('philosophy_method_closing', models.CharField(blank=True, max_length=200)),
                ('philosophy_pillars', models.JSONField(blank=True, default=list)),
                ('values', models.JSONField(blank=True, default=list)),
                ('mission_title', models.CharField(default='Misión', max_length=80)),
                ('mission_statement', models.TextField()),
                ('vision_title', models.CharField(default='Visión', max_length=80)),
                ('vision_statement', models.TextField()),
                ('mission_image', models.ImageField(blank=True, null=True, upload_to='about/page/mission/')),
                ('mission_image_external_url', models.URLField(blank=True, max_length=500)),
                ('vision_image', models.ImageField(blank=True, null=True, upload_to='about/page/vision/')),
                ('vision_image_external_url', models.URLField(blank=True, max_length=500)),
                ('team_eyebrow', models.CharField(default='Equipo Total Living', max_length=80)),
                ('team_title', models.CharField(default='El equipo detrás de cada decisión', max_length=160)),
                ('org_eyebrow', models.CharField(default='Organigrama', max_length=80)),
                ('org_title', models.CharField(blank=True, max_length=160)),
                ('org_chart', models.JSONField(blank=True, default=dict)),
                ('cta_eyebrow', models.CharField(blank=True, max_length=80)),
                ('cta_title', models.CharField(blank=True, max_length=200)),
                ('cta_body', models.TextField(blank=True)),
                ('cta_primary_label', models.CharField(blank=True, max_length=60)),
                ('cta_primary_url', models.CharField(blank=True, max_length=200)),
                ('cta_secondary_label', models.CharField(blank=True, max_length=60)),
                ('cta_secondary_url', models.CharField(blank=True, max_length=200)),
                ('section_nav', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Nosotros (textos)',
                'verbose_name_plural': 'Página Nosotros (textos)',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('role', models.CharField(max_length=160)),
                ('department', models.CharField(blank=True, max_length=120)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='about/team/')),
                ('photo_external_url', models.URLField(blank=True, max_length=500)),
                ('socials', models.JSONField(blank=True, default=list)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Miembro del equipo',
                'verbose_name_plural': 'Equipo Total Living',
                'ordering': ['order', 'name'],
            },
        ),
    ]
