# Generated by Django 6.0.6 on 2026-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='content_en',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
