# Generated by Django 6.0.6 on 2026-07-13 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutpage_content_en'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='content_en',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
