# Generated by Django 6.0.6 on 2026-07-11 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('name', models.CharField(choices=[('Zona Campanario / Altozano', 'Zona Campanario / Altozano'), ('Zona Centro / Querétaro Tradicional', 'Zona Centro / Querétaro Tradicional'), ('Zona Centro Sur / Sur de Querétaro', 'Zona Centro Sur / Sur de Querétaro'), ('Zona Ciudad del Sol / Poniente', 'Zona Ciudad del Sol / Poniente'), ('Zona Corregidora', 'Zona Corregidora'), ('Zona El Refugio / Norte de El Marqués', 'Zona El Refugio / Norte de El Marqués'), ('Zona Juriquilla / Jurica', 'Zona Juriquilla / Jurica'), ('Zona Zibatá / Zakia', 'Zona Zibatá / Zakia')], max_length=120, unique=True)),
                ('growth_label', models.CharField(choices=[('Plusvalía premium', 'Plusvalía premium'), ('Crecimiento alto', 'Crecimiento alto'), ('Crecimiento medio', 'Crecimiento medio'), ('Emergente', 'Emergente')], default='Crecimiento medio', max_length=40)),
                ('description', models.TextField()),
                ('sub_zones', models.JSONField(blank=True, default=list)),
                ('image', models.ImageField(blank=True, null=True, upload_to='zones/covers/')),
                ('image_external_url', models.URLField(blank=True, max_length=500)),
                ('is_published', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Zona',
                'verbose_name_plural': 'Zonas',
                'ordering': ['order', 'name'],
            },
        ),
    ]
