# Generated by Django 6.0.6 on 2026-07-11 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZonesPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(max_length=80)),
                ('hero_title', models.CharField(max_length=160)),
                ('hero_subtitle', models.TextField()),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='zones/page/hero/')),
                ('hero_image_external_url', models.URLField(blank=True, max_length=500)),
                ('scroll_hint', models.CharField(default='Desplázate', max_length=40)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página de zonas (textos)',
                'verbose_name_plural': 'Página de zonas (textos)',
            },
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=120, unique=True),
        ),
    ]
