# Generated by Django 6.0.6 on 2026-07-13 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zones', '0002_zonespage_alter_zone_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='content_en',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='zonespage',
            name='content_en',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
