# Generated by Django 6.0.6 on 2026-07-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsesoriaPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_eyebrow', models.CharField(blank=True, max_length=120)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_subtitle', models.TextField(blank=True)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='asesoria/page/hero/')),
                ('hero_image_external_url', models.URLField(blank=True, max_length=500)),
                ('services_title', models.CharField(default='Servicios de Asesoría Inmobiliaria', max_length=200)),
                ('tabs', models.JSONField(blank=True, default=list)),
                ('pillars', models.JSONField(blank=True, default=list)),
                ('cta_title', models.CharField(blank=True, max_length=200)),
                ('cta_subtitle', models.TextField(blank=True)),
                ('cta_label', models.CharField(blank=True, max_length=80)),
                ('cta_whatsapp_message', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Página Asesoría (textos)',
                'verbose_name_plural': 'Página Asesoría (textos)',
            },
        ),
    ]
